# Generated by Django 5.2.7 on 2025-10-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("author", models.CharField(max_length=120)),
                ("content", models.TextField()),
                ("data_published", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
