# Generated by Django 5.2.7 on 2025-10-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="data_published",
            field=models.DateTimeField(),
        ),
    ]
